import { BCheckBox } from 'b-check-box';
import { BComboBox } from 'b-combo-box';
import { BDateTimePicker } from 'b-datetime-picker';
import { BBusinessDateTimeComponent } from 'b-business-datetime-component';
import { BInput } from 'b-input';
import { BInputMask } from 'b-input-mask';
import { BAccountComponent } from 'b-account-component';
import { BCard } from 'b-card';
import { BLabel } from 'b-label';
import { BMernisComponent } from 'b-mernis-component';
import { BBranchComponent } from 'b-branch-component';
import { BParameterComponent } from 'b-parameter-component';
import { BWorkgroupUserComponent } from 'b-workgroup-user-component';
import { BWorkgroupComponent } from 'b-workgroup-component';
import { BBankComponent } from 'b-bank-component';
import { BCommissionComponent } from 'b-commission-component';
import { BFECComponent } from 'b-fec-component';
import { BMoney } from 'b-money';
import { BThirdPartyComponent } from 'b-third-party-component';
import { BThirdPartyRelationPersonsComponent } from 'b-third-party-relation-persons-component';
import { BInputNumeric } from 'b-input-numeric';
import { BPersonComponent } from 'b-person-component';
import { BUserComponent } from 'b-user-component';
import { BChannelComponent } from 'b-channel-component';
import { BProductBrowser } from 'b-product-browser-component';
import { BCreditCardComponent } from 'b-credit-card-component';
import { BExcelBrowser } from 'b-excel-browser';
import { BResourceBrowser } from 'b-resource-browser';
import { BFinancialSegmentBrowser } from 'b-financial-segment-browser';
import { BAccessPointBrowser } from 'b-access-point-browser';
import { BGridActionPanel } from 'b-grid-action-panel';
import { BToggle } from 'b-toggle';

export function getModule(moduleName) {
  switch (moduleName) {
    case 'b-check-box': return BCheckBox;
    case 'b-combo-box': return BComboBox;
    case 'b-datetime-picker': return BDateTimePicker;
    case 'b-business-datetime-component': return BBusinessDateTimeComponent;
    case 'b-input': return BInput;
    case 'b-account-component': return BAccountComponent;
    case 'b-card': return BCard;
    case 'b-input-mask': return BInputMask;
    case 'b-label': return BLabel;
    case 'b-mernis-component': return BMernisComponent;
    case 'b-branch-component': return BBranchComponent;
    case 'b-parameter-component': return BParameterComponent;
    case 'b-workgroup-user-component': return BWorkgroupUserComponent;
    case 'b-workgroup-component': return BWorkgroupComponent;
    case 'b-bank-component': return BBankComponent;
    case 'b-commission-component': return BCommissionComponent;
    case 'b-fec-component': return BFECComponent;
    case 'b-money': return BMoney;
    case 'b-third-party-component': return BThirdPartyComponent;
    case 'b-third-party-relation-persons-component': return BThirdPartyRelationPersonsComponent;
    case 'b-input-numeric': return BInputNumeric;
    case 'b-person-component': return BPersonComponent;
    case 'b-user-component': return BUserComponent;
    case 'b-channel-component': return BChannelComponent;
    case 'b-product-browser-component': return BProductBrowser;
    case 'b-credit-card-component': return BCreditCardComponent;
    case 'b-excel-browser': return BExcelBrowser;
    case 'b-resource-browser': return BResourceBrowser;
    case 'b-financial-segment-browser': return BFinancialSegmentBrowser;
    case 'b-access-point-browser': return BAccessPointBrowser;
    case 'b-grid-action-panel': return BGridActionPanel;
    case 'b-toggle': return BToggle;
  }
}
