/**
 * Generated by b-build module
 */
import {
  publishFiles,
  publishBuildFiles,
  tscompile,
  webpackVendor,
  webpack,
  npmInstallAndUpdate,
  updateTypings,
  publishFilesAutomation
} from './build_scripts/compose';

var gulp = require('gulp'),
  gutil = require('gulp-util');

gulp.task('build', function () {
  gutil.log('Build started.');
  publishFiles();
  tscompile();
  webpack();
  gutil.log('Build finished successfully.');
});

gulp.task('fullbuild', function () {
  gutil.log('Full build started.');
  publishFilesAutomation();
  npmInstallAndUpdate();
  tscompile();
  webpackVendor();
  webpack();
  gutil.log('Full build finished successfully.');
});

gulp.task('update-typings', function () {
  gutil.log('Update Typings started.');
  updateTypings();
  gutil.log('Update Typings finished successfully.');
});

gulp.task('build-automation', function () {
  gutil.log('Build Automation started.');
  publishFiles();
  gutil.log('Build Automation finished successfully.');
});

gulp.task('build-automation-new', function () {
  gutil.log('Build Automation New started.');
  publishBuildFiles();
  tscompile(true);
  gutil.log('Build Automation New finished successfully.');
});
